name: "publish"

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://regsitry.npmjs.org
      - name: Setup checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup npmrc
        run: | 
          echo -e "@fullexpression:registry=https://npm.pkg.github.com/fullexpression\n//npm.pkg.github.com/:_authToken=${{secrets.NPM_AUTH_TOKEN}}\nregistry=https://registry.npmjs.org" > .npmrc
          git config --global core.excludesfile .npmrc
      - name: Install packages
        run: npm install
      - name: Setting git author
        run: | 
          git config --global user.email "ricardo1992rocha@gmail.com"
          git config --global user.name "Ricardo Rocha"
      - name: Increase patch version
        working-directory: ./
        run: |
          ls -l
          npm version patch --force
      - name: Build
        run: npm run build
      - name: Commit new version
        working-directory: ./
        run: git push 
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
